services:
  server:
    build:
      context: ./server
    container_name: fl_server
    ports:
      - "50051:50051"
      - "8080:8080" # REST
    environment:
      - EXPECTED_CLIENTS=3
    networks:
      - flnet

  client1:
    image: fl_client_image
    container_name: fl_client_1
    volumes:
      - ./client_node:/app
    working_dir: /app
    command: ["python", "main.py"]
    environment:
      - SERVER_HOST=fl_server
      - CLIENT_ID=client1
      - SIMULATE_OFFLOAD=false
    depends_on:
      - server
    networks:
      - flnet

  client2:
    image: fl_client_image
    container_name: fl_client_2
    volumes:
      - ./client_node:/app
    working_dir: /app
    command: ["python", "main.py"]
    environment:
      - SERVER_HOST=fl_server
      - CLIENT_ID=client2
      - SIMULATE_OFFLOAD=false
    depends_on:
      - server
    networks:
      - flnet

  client3:
    image: fl_client_image
    container_name: fl_client_3
    volumes:
      - ./client_node:/app
    working_dir: /app
    command: ["python", "main.py"]
    environment:
      - SERVER_HOST=fl_server
      - CLIENT_ID=client3
      - SIMULATE_OFFLOAD=false
    depends_on:
      - server
    networks:
      - flnet

  client4:
    image: fl_client_image
    container_name: fl_client_4
    volumes:
      - ./client_node:/app
    working_dir: /app
    command: ["python", "main.py"]
    environment:
      - SERVER_HOST=fl_server
      - CLIENT_ID=client4
      - SIMULATE_OFFLOAD=true
    depends_on:
      - server
    networks:
      - flnet

  frontend:
    build:
      context: ./fl-frontend
    container_name: fl_frontend
    ports:
      - "3000:3000"
    environment:
      - API_BASE=http://fl_server:8080
    networks:
      - flnet

networks:
  flnet:
    name: fl_network
