# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fl.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66l.proto\x12\x02\x66l\"\xa9\x01\n\x0c\x43lientUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63pu_percent\x18\x02 \x01(\x01\x12\x16\n\x0ememory_used_mb\x18\x03 \x01(\x01\x12\x16\n\x0ememory_percent\x18\x04 \x01(\x01\x12\x16\n\x0enet_sent_bytes\x18\x05 \x01(\x03\x12\x16\n\x0enet_recv_bytes\x18\x06 \x01(\x03\x12\x11\n\toffloaded\x18\x07 \x01(\x08\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2B\n\x0f\x46\x65\x64\x65ratedLogger\x12/\n\x10SendClientUpdate\x12\x10.fl.ClientUpdate\x1a\x07.fl.Ack\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTUPDATE']._serialized_start=17
  _globals['_CLIENTUPDATE']._serialized_end=186
  _globals['_ACK']._serialized_start=188
  _globals['_ACK']._serialized_end=210
  _globals['_FEDERATEDLOGGER']._serialized_start=212
  _globals['_FEDERATEDLOGGER']._serialized_end=278
# @@protoc_insertion_point(module_scope)
