# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fl.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66l.proto\x12\x02\x66l\"\xa9\x01\n\x0c\x43lientUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63pu_percent\x18\x02 \x01(\x01\x12\x16\n\x0ememory_used_mb\x18\x03 \x01(\x01\x12\x16\n\x0ememory_percent\x18\x04 \x01(\x01\x12\x16\n\x0enet_sent_bytes\x18\x05 \x01(\x03\x12\x16\n\x0enet_recv_bytes\x18\x06 \x01(\x03\x12\x11\n\toffloaded\x18\x07 \x01(\x08\"\x8c\x01\n\x0bModelUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12-\n\x07weights\x18\x02 \x03(\x0b\x32\x1c.fl.ModelUpdate.WeightsEntry\x1a;\n\x0cWeightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.fl.Weights:\x02\x38\x01\"\x19\n\x07Weights\x12\x0e\n\x06values\x18\x01 \x03(\x02\"#\n\x12GlobalModelRequest\x12\r\n\x05round\x18\x01 \x01(\x03\"\x88\x01\n\x0bGlobalModel\x12\r\n\x05round\x18\x01 \x01(\x03\x12-\n\x07weights\x18\x02 \x03(\x0b\x32\x1c.fl.GlobalModel.WeightsEntry\x1a;\n\x0cWeightsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.fl.Weights:\x02\x38\x01\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2\xae\x01\n\x0f\x46\x65\x64\x65ratedLogger\x12/\n\x10SendClientUpdate\x12\x10.fl.ClientUpdate\x1a\x07.fl.Ack\"\x00\x12-\n\x0fSendModelUpdate\x12\x0f.fl.ModelUpdate\x1a\x07.fl.Ack\"\x00\x12;\n\x0eGetGlobalModel\x12\x16.fl.GlobalModelRequest\x1a\x0f.fl.GlobalModel\"\x00\x42\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_MODELUPDATE_WEIGHTSENTRY']._loaded_options = None
  _globals['_MODELUPDATE_WEIGHTSENTRY']._serialized_options = b'8\001'
  _globals['_GLOBALMODEL_WEIGHTSENTRY']._loaded_options = None
  _globals['_GLOBALMODEL_WEIGHTSENTRY']._serialized_options = b'8\001'
  _globals['_CLIENTUPDATE']._serialized_start=17
  _globals['_CLIENTUPDATE']._serialized_end=186
  _globals['_MODELUPDATE']._serialized_start=189
  _globals['_MODELUPDATE']._serialized_end=329
  _globals['_MODELUPDATE_WEIGHTSENTRY']._serialized_start=270
  _globals['_MODELUPDATE_WEIGHTSENTRY']._serialized_end=329
  _globals['_WEIGHTS']._serialized_start=331
  _globals['_WEIGHTS']._serialized_end=356
  _globals['_GLOBALMODELREQUEST']._serialized_start=358
  _globals['_GLOBALMODELREQUEST']._serialized_end=393
  _globals['_GLOBALMODEL']._serialized_start=396
  _globals['_GLOBALMODEL']._serialized_end=532
  _globals['_GLOBALMODEL_WEIGHTSENTRY']._serialized_start=270
  _globals['_GLOBALMODEL_WEIGHTSENTRY']._serialized_end=329
  _globals['_ACK']._serialized_start=534
  _globals['_ACK']._serialized_end=556
  _globals['_FEDERATEDLOGGER']._serialized_start=559
  _globals['_FEDERATEDLOGGER']._serialized_end=733
# @@protoc_insertion_point(module_scope)
