// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: fl.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedMb  float64                `protobuf:"fixed64,3,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	NetSentBytes  int64                  `protobuf:"varint,5,opt,name=net_sent_bytes,json=netSentBytes,proto3" json:"net_sent_bytes,omitempty"`
	NetRecvBytes  int64                  `protobuf:"varint,6,opt,name=net_recv_bytes,json=netRecvBytes,proto3" json:"net_recv_bytes,omitempty"`
	Offloaded     bool                   `protobuf:"varint,7,opt,name=offloaded,proto3" json:"offloaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientUpdate) Reset() {
	*x = ClientUpdate{}
	mi := &file_fl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUpdate) ProtoMessage() {}

func (x *ClientUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_fl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUpdate.ProtoReflect.Descriptor instead.
func (*ClientUpdate) Descriptor() ([]byte, []int) {
	return file_fl_proto_rawDescGZIP(), []int{0}
}

func (x *ClientUpdate) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientUpdate) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ClientUpdate) GetMemoryUsedMb() float64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *ClientUpdate) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ClientUpdate) GetNetSentBytes() int64 {
	if x != nil {
		return x.NetSentBytes
	}
	return 0
}

func (x *ClientUpdate) GetNetRecvBytes() int64 {
	if x != nil {
		return x.NetRecvBytes
	}
	return 0
}

func (x *ClientUpdate) GetOffloaded() bool {
	if x != nil {
		return x.Offloaded
	}
	return false
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_fl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_fl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_fl_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_fl_proto protoreflect.FileDescriptor

const file_fl_proto_rawDesc = "" +
	"\n" +
	"\bfl.proto\x12\x02fl\"\x83\x02\n" +
	"\fClientUpdate\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12$\n" +
	"\x0ememory_used_mb\x18\x03 \x01(\x01R\fmemoryUsedMb\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\x12$\n" +
	"\x0enet_sent_bytes\x18\x05 \x01(\x03R\fnetSentBytes\x12$\n" +
	"\x0enet_recv_bytes\x18\x06 \x01(\x03R\fnetRecvBytes\x12\x1c\n" +
	"\toffloaded\x18\a \x01(\bR\toffloaded\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2B\n" +
	"\x0fFederatedLogger\x12/\n" +
	"\x10SendClientUpdate\x12\x10.fl.ClientUpdate\x1a\a.fl.Ack\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_fl_proto_rawDescOnce sync.Once
	file_fl_proto_rawDescData []byte
)

func file_fl_proto_rawDescGZIP() []byte {
	file_fl_proto_rawDescOnce.Do(func() {
		file_fl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fl_proto_rawDesc), len(file_fl_proto_rawDesc)))
	})
	return file_fl_proto_rawDescData
}

var file_fl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fl_proto_goTypes = []any{
	(*ClientUpdate)(nil), // 0: fl.ClientUpdate
	(*Ack)(nil),          // 1: fl.Ack
}
var file_fl_proto_depIdxs = []int32{
	0, // 0: fl.FederatedLogger.SendClientUpdate:input_type -> fl.ClientUpdate
	1, // 1: fl.FederatedLogger.SendClientUpdate:output_type -> fl.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fl_proto_init() }
func file_fl_proto_init() {
	if File_fl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fl_proto_rawDesc), len(file_fl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fl_proto_goTypes,
		DependencyIndexes: file_fl_proto_depIdxs,
		MessageInfos:      file_fl_proto_msgTypes,
	}.Build()
	File_fl_proto = out.File
	file_fl_proto_goTypes = nil
	file_fl_proto_depIdxs = nil
}
