// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: fl.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedMb  float64                `protobuf:"fixed64,3,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	NetSentBytes  int64                  `protobuf:"varint,5,opt,name=net_sent_bytes,json=netSentBytes,proto3" json:"net_sent_bytes,omitempty"`
	NetRecvBytes  int64                  `protobuf:"varint,6,opt,name=net_recv_bytes,json=netRecvBytes,proto3" json:"net_recv_bytes,omitempty"`
	Offloaded     bool                   `protobuf:"varint,7,opt,name=offloaded,proto3" json:"offloaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientUpdate) Reset() {
	*x = ClientUpdate{}
	mi := &file_fl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUpdate) ProtoMessage() {}

func (x *ClientUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_fl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUpdate.ProtoReflect.Descriptor instead.
func (*ClientUpdate) Descriptor() ([]byte, []int) {
	return file_fl_proto_rawDescGZIP(), []int{0}
}

func (x *ClientUpdate) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientUpdate) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ClientUpdate) GetMemoryUsedMb() float64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *ClientUpdate) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ClientUpdate) GetNetSentBytes() int64 {
	if x != nil {
		return x.NetSentBytes
	}
	return 0
}

func (x *ClientUpdate) GetNetRecvBytes() int64 {
	if x != nil {
		return x.NetRecvBytes
	}
	return 0
}

func (x *ClientUpdate) GetOffloaded() bool {
	if x != nil {
		return x.Offloaded
	}
	return false
}

type ModelUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Weights       map[string]*Weights    `protobuf:"bytes,2,rep,name=weights,proto3" json:"weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelUpdate) Reset() {
	*x = ModelUpdate{}
	mi := &file_fl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUpdate) ProtoMessage() {}

func (x *ModelUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_fl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUpdate.ProtoReflect.Descriptor instead.
func (*ModelUpdate) Descriptor() ([]byte, []int) {
	return file_fl_proto_rawDescGZIP(), []int{1}
}

func (x *ModelUpdate) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ModelUpdate) GetWeights() map[string]*Weights {
	if x != nil {
		return x.Weights
	}
	return nil
}

type Weights struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weights) Reset() {
	*x = Weights{}
	mi := &file_fl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weights) ProtoMessage() {}

func (x *Weights) ProtoReflect() protoreflect.Message {
	mi := &file_fl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weights.ProtoReflect.Descriptor instead.
func (*Weights) Descriptor() ([]byte, []int) {
	return file_fl_proto_rawDescGZIP(), []int{2}
}

func (x *Weights) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type GlobalModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// round can be empty or specific
	Round         int64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalModelRequest) Reset() {
	*x = GlobalModelRequest{}
	mi := &file_fl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalModelRequest) ProtoMessage() {}

func (x *GlobalModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalModelRequest.ProtoReflect.Descriptor instead.
func (*GlobalModelRequest) Descriptor() ([]byte, []int) {
	return file_fl_proto_rawDescGZIP(), []int{3}
}

func (x *GlobalModelRequest) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type GlobalModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int64                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Weights       map[string]*Weights    `protobuf:"bytes,2,rep,name=weights,proto3" json:"weights,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalModel) Reset() {
	*x = GlobalModel{}
	mi := &file_fl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalModel) ProtoMessage() {}

func (x *GlobalModel) ProtoReflect() protoreflect.Message {
	mi := &file_fl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalModel.ProtoReflect.Descriptor instead.
func (*GlobalModel) Descriptor() ([]byte, []int) {
	return file_fl_proto_rawDescGZIP(), []int{4}
}

func (x *GlobalModel) GetRound() int64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *GlobalModel) GetWeights() map[string]*Weights {
	if x != nil {
		return x.Weights
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_fl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_fl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_fl_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_fl_proto protoreflect.FileDescriptor

const file_fl_proto_rawDesc = "" +
	"\n" +
	"\bfl.proto\x12\x02fl\"\x83\x02\n" +
	"\fClientUpdate\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12$\n" +
	"\x0ememory_used_mb\x18\x03 \x01(\x01R\fmemoryUsedMb\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\x12$\n" +
	"\x0enet_sent_bytes\x18\x05 \x01(\x03R\fnetSentBytes\x12$\n" +
	"\x0enet_recv_bytes\x18\x06 \x01(\x03R\fnetRecvBytes\x12\x1c\n" +
	"\toffloaded\x18\a \x01(\bR\toffloaded\"\xab\x01\n" +
	"\vModelUpdate\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x126\n" +
	"\aweights\x18\x02 \x03(\v2\x1c.fl.ModelUpdate.WeightsEntryR\aweights\x1aG\n" +
	"\fWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.fl.WeightsR\x05value:\x028\x01\"!\n" +
	"\aWeights\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"*\n" +
	"\x12GlobalModelRequest\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x03R\x05round\"\xa4\x01\n" +
	"\vGlobalModel\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x03R\x05round\x126\n" +
	"\aweights\x18\x02 \x03(\v2\x1c.fl.GlobalModel.WeightsEntryR\aweights\x1aG\n" +
	"\fWeightsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.fl.WeightsR\x05value:\x028\x01\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xae\x01\n" +
	"\x0fFederatedLogger\x12/\n" +
	"\x10SendClientUpdate\x12\x10.fl.ClientUpdate\x1a\a.fl.Ack\"\x00\x12-\n" +
	"\x0fSendModelUpdate\x12\x0f.fl.ModelUpdate\x1a\a.fl.Ack\"\x00\x12;\n" +
	"\x0eGetGlobalModel\x12\x16.fl.GlobalModelRequest\x1a\x0f.fl.GlobalModel\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_fl_proto_rawDescOnce sync.Once
	file_fl_proto_rawDescData []byte
)

func file_fl_proto_rawDescGZIP() []byte {
	file_fl_proto_rawDescOnce.Do(func() {
		file_fl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fl_proto_rawDesc), len(file_fl_proto_rawDesc)))
	})
	return file_fl_proto_rawDescData
}

var file_fl_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_fl_proto_goTypes = []any{
	(*ClientUpdate)(nil),       // 0: fl.ClientUpdate
	(*ModelUpdate)(nil),        // 1: fl.ModelUpdate
	(*Weights)(nil),            // 2: fl.Weights
	(*GlobalModelRequest)(nil), // 3: fl.GlobalModelRequest
	(*GlobalModel)(nil),        // 4: fl.GlobalModel
	(*Ack)(nil),                // 5: fl.Ack
	nil,                        // 6: fl.ModelUpdate.WeightsEntry
	nil,                        // 7: fl.GlobalModel.WeightsEntry
}
var file_fl_proto_depIdxs = []int32{
	6, // 0: fl.ModelUpdate.weights:type_name -> fl.ModelUpdate.WeightsEntry
	7, // 1: fl.GlobalModel.weights:type_name -> fl.GlobalModel.WeightsEntry
	2, // 2: fl.ModelUpdate.WeightsEntry.value:type_name -> fl.Weights
	2, // 3: fl.GlobalModel.WeightsEntry.value:type_name -> fl.Weights
	0, // 4: fl.FederatedLogger.SendClientUpdate:input_type -> fl.ClientUpdate
	1, // 5: fl.FederatedLogger.SendModelUpdate:input_type -> fl.ModelUpdate
	3, // 6: fl.FederatedLogger.GetGlobalModel:input_type -> fl.GlobalModelRequest
	5, // 7: fl.FederatedLogger.SendClientUpdate:output_type -> fl.Ack
	5, // 8: fl.FederatedLogger.SendModelUpdate:output_type -> fl.Ack
	4, // 9: fl.FederatedLogger.GetGlobalModel:output_type -> fl.GlobalModel
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_fl_proto_init() }
func file_fl_proto_init() {
	if File_fl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fl_proto_rawDesc), len(file_fl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fl_proto_goTypes,
		DependencyIndexes: file_fl_proto_depIdxs,
		MessageInfos:      file_fl_proto_msgTypes,
	}.Build()
	File_fl_proto = out.File
	file_fl_proto_goTypes = nil
	file_fl_proto_depIdxs = nil
}
