// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: fl.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FederatedLogger_SendClientUpdate_FullMethodName = "/fl.FederatedLogger/SendClientUpdate"
	FederatedLogger_SendModelUpdate_FullMethodName  = "/fl.FederatedLogger/SendModelUpdate"
	FederatedLogger_GetGlobalModel_FullMethodName   = "/fl.FederatedLogger/GetGlobalModel"
)

// FederatedLoggerClient is the client API for FederatedLogger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FederatedLoggerClient interface {
	SendClientUpdate(ctx context.Context, in *ClientUpdate, opts ...grpc.CallOption) (*Ack, error)
	SendModelUpdate(ctx context.Context, in *ModelUpdate, opts ...grpc.CallOption) (*Ack, error)
	GetGlobalModel(ctx context.Context, in *GlobalModelRequest, opts ...grpc.CallOption) (*GlobalModel, error)
}

type federatedLoggerClient struct {
	cc grpc.ClientConnInterface
}

func NewFederatedLoggerClient(cc grpc.ClientConnInterface) FederatedLoggerClient {
	return &federatedLoggerClient{cc}
}

func (c *federatedLoggerClient) SendClientUpdate(ctx context.Context, in *ClientUpdate, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, FederatedLogger_SendClientUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedLoggerClient) SendModelUpdate(ctx context.Context, in *ModelUpdate, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, FederatedLogger_SendModelUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedLoggerClient) GetGlobalModel(ctx context.Context, in *GlobalModelRequest, opts ...grpc.CallOption) (*GlobalModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GlobalModel)
	err := c.cc.Invoke(ctx, FederatedLogger_GetGlobalModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederatedLoggerServer is the server API for FederatedLogger service.
// All implementations must embed UnimplementedFederatedLoggerServer
// for forward compatibility.
type FederatedLoggerServer interface {
	SendClientUpdate(context.Context, *ClientUpdate) (*Ack, error)
	SendModelUpdate(context.Context, *ModelUpdate) (*Ack, error)
	GetGlobalModel(context.Context, *GlobalModelRequest) (*GlobalModel, error)
	mustEmbedUnimplementedFederatedLoggerServer()
}

// UnimplementedFederatedLoggerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederatedLoggerServer struct{}

func (UnimplementedFederatedLoggerServer) SendClientUpdate(context.Context, *ClientUpdate) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendClientUpdate not implemented")
}
func (UnimplementedFederatedLoggerServer) SendModelUpdate(context.Context, *ModelUpdate) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendModelUpdate not implemented")
}
func (UnimplementedFederatedLoggerServer) GetGlobalModel(context.Context, *GlobalModelRequest) (*GlobalModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalModel not implemented")
}
func (UnimplementedFederatedLoggerServer) mustEmbedUnimplementedFederatedLoggerServer() {}
func (UnimplementedFederatedLoggerServer) testEmbeddedByValue()                         {}

// UnsafeFederatedLoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederatedLoggerServer will
// result in compilation errors.
type UnsafeFederatedLoggerServer interface {
	mustEmbedUnimplementedFederatedLoggerServer()
}

func RegisterFederatedLoggerServer(s grpc.ServiceRegistrar, srv FederatedLoggerServer) {
	// If the following call pancis, it indicates UnimplementedFederatedLoggerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FederatedLogger_ServiceDesc, srv)
}

func _FederatedLogger_SendClientUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedLoggerServer).SendClientUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederatedLogger_SendClientUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedLoggerServer).SendClientUpdate(ctx, req.(*ClientUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedLogger_SendModelUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedLoggerServer).SendModelUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederatedLogger_SendModelUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedLoggerServer).SendModelUpdate(ctx, req.(*ModelUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedLogger_GetGlobalModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedLoggerServer).GetGlobalModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederatedLogger_GetGlobalModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedLoggerServer).GetGlobalModel(ctx, req.(*GlobalModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FederatedLogger_ServiceDesc is the grpc.ServiceDesc for FederatedLogger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FederatedLogger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fl.FederatedLogger",
	HandlerType: (*FederatedLoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendClientUpdate",
			Handler:    _FederatedLogger_SendClientUpdate_Handler,
		},
		{
			MethodName: "SendModelUpdate",
			Handler:    _FederatedLogger_SendModelUpdate_Handler,
		},
		{
			MethodName: "GetGlobalModel",
			Handler:    _FederatedLogger_GetGlobalModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fl.proto",
}
